package dev.duma.android.hal.plugins.sunmi.tms.device

import android.content.Context
import dev.duma.android.hal.contract.DescriptorGroup
import dev.duma.android.hal.contract.EventDescriptor
import dev.duma.android.hal.contract.MethodDescriptor
import dev.duma.android.hal.contract.PluginDescriptor
import dev.duma.android.hal.contract.stripExperimental
import dev.duma.android.hal.contract.CommandResult
import dev.duma.android.hal.plugins.sunmi.tms.device.handler.*
import dev.duma.android.hal.plugins.sunmi.tms.base.BaseTmsPlugin

class SunmiTmsDevicePlugin(context: Context? = null) : BaseTmsPlugin(context) {

    override val pluginId = "sunmi.tms.device"
    override val version = 1

    private val deviceInfoHandler by lazy { DeviceInfoHandler(tmsApi) }
    private val deviceManagerHandler by lazy { DeviceManagerHandler(tmsApi) }
    private val deviceRunningInfoHandler by lazy { DeviceRunningInfoHandler(tmsApi, ::emitEvent) }

    override fun getCapabilities() = listOf("sunmi.tms.device")

    override fun getDescriptor() = fullDescriptor().let {
        if (BuildConfig.WITH_EXPERIMENTAL) it else it.stripExperimental()
    }

    private fun fullDescriptor() = PluginDescriptor(
        pluginId = pluginId,
        name = "Sunmi: TMS (Device)",
        version = version,
        capabilities = getCapabilities(),
        groups = listOf(
            DescriptorGroup(
                name = "Device Info",
                methods = buildDeviceInfoMethods(),
            ),
            DescriptorGroup(
                name = "Device Manager",
                methods = buildDeviceManagerMethods(),
            ),
            DescriptorGroup(
                name = "Runtime",
                methods = buildRuntimeMethods(),
                events = listOf(
                    EventDescriptor(
                        "sunmi.tms.device.runtime.gpsLocationChanged",
                        "Real-time GPS result from getGPSLocationWithTimeout",
                        "sunmi.tms.device",
                        exampleEvent = """{"longitude":"116.397128","latitude":"39.916527","altitude":"50.0","speed":"0.0","bearing":"0.0"}"""
                    ),
                    EventDescriptor(
                        "sunmi.tms.device.runtime.networkLocationChanged",
                        "Real-time network-based location result from getNetworkLocationWithTimeout",
                        "sunmi.tms.device",
                        exampleEvent = """{"longitude":"116.397128","latitude":"39.916527","altitude":"50.0","speed":"0.0","bearing":"0.0"}"""
                    )
                ),
            ),
        )
    )

    override suspend fun onExecute(method: String, params: String): CommandResult = guardedExecute {
        val module = method.removePrefix("sunmi.tms.device.").substringBefore(".")
        when (module) {
            "device_info"    -> deviceInfoHandler.handle(method, params)
            "device_manager" -> deviceManagerHandler.handle(method, params)
            "runtime"        -> deviceRunningInfoHandler.handle(method, params)
            else             -> CommandResult.unsupportedMethod(method)
        }
    }

    private fun buildDeviceInfoMethods() = listOf(
        MethodDescriptor("sunmi.tms.device.device_info.getSerialNo", "Gets device serial number", "sunmi.tms.device",
            exampleParameters = "{}",
            exampleOutput = """{"result":"XXXXXXXXXXXX"}"""),
        MethodDescriptor("sunmi.tms.device.device_info.getModel", "Gets device model", "sunmi.tms.device",
            exampleParameters = "{}",
            exampleOutput = """{"result":"T2s"}"""),
        MethodDescriptor("sunmi.tms.device.device_info.getManufacture", "Gets device manufacturer name", "sunmi.tms.device",
            exampleParameters = "{}",
            exampleOutput = """{"result":"SUNMI"}"""),
        MethodDescriptor("sunmi.tms.device.device_info.getBrand", "Gets device brand", "sunmi.tms.device",
            exampleParameters = "{}",
            exampleOutput = """{"result":"SUNMI"}"""),
        MethodDescriptor("sunmi.tms.device.device_info.getAndroidOSVersion", "Gets Android OS version", "sunmi.tms.device",
            exampleParameters = "{}",
            exampleOutput = """{"result":"11"}"""),
        MethodDescriptor("sunmi.tms.device.device_info.getAndroidKernelVersion", "Gets Android kernel version", "sunmi.tms.device",
            exampleParameters = "{}",
            exampleOutput = """{"result":"4.14.98"}"""),
        MethodDescriptor("sunmi.tms.device.device_info.getROMVersion", "Gets ROM version", "sunmi.tms.device",
            exampleParameters = "{}",
            exampleOutput = """{"result":"1.0.0"}"""),
        MethodDescriptor("sunmi.tms.device.device_info.getFirmwareVersion", "Gets firmware version", "sunmi.tms.device",
            exampleParameters = "{}",
            exampleOutput = """{"result":"1.0.0"}"""),
        MethodDescriptor("sunmi.tms.device.device_info.getHardwareVersion", "Gets hardware version", "sunmi.tms.device",
            exampleParameters = "{}",
            exampleOutput = """{"result":"1.0.0"}"""),
        MethodDescriptor("sunmi.tms.device.device_info.getSDKVersion", "Gets Android SDK version", "sunmi.tms.device",
            exampleParameters = "{}",
            exampleOutput = """{"result":"30"}"""),
        MethodDescriptor("sunmi.tms.device.device_info.getSunmiOsVersion", "Gets Sunmi OS version", "sunmi.tms.device",
            exampleParameters = "{}",
            exampleOutput = """{"result":"3.0.0"}"""),
        MethodDescriptor("sunmi.tms.device.device_info.getSystemBuildDisplayId", "Gets system build DisplayId", "sunmi.tms.device",
            exampleParameters = "{}",
            exampleOutput = """{"result":"T2s_TW_V1.0.0_20230101"}"""),
        MethodDescriptor("sunmi.tms.device.device_info.getMemoryOccupation", "Gets used system memory in bytes", "sunmi.tms.device",
            exampleParameters = "{}",
            exampleOutput = """{"result":1073741824}"""),
        MethodDescriptor("sunmi.tms.device.device_info.getMac", "Gets Wi-Fi MAC address (Wi-Fi must be on)", "sunmi.tms.device",
            exampleParameters = "{}",
            exampleOutput = """{"result":"AA:BB:CC:DD:EE:FF"}"""),
        MethodDescriptor("sunmi.tms.device.device_info.getDeviceBluetoothMacAddress", "Gets Bluetooth MAC address (BT must be connected)", "sunmi.tms.device",
            exampleParameters = "{}",
            exampleOutput = """{"result":"AA:BB:CC:DD:EE:FF"}"""),
        MethodDescriptor("sunmi.tms.device.device_info.getIpAddresses", "Gets device IP addresses", "sunmi.tms.device",
            exampleParameters = "{}",
            exampleOutput = """{"result":"192.168.1.100"}"""),
        MethodDescriptor("sunmi.tms.device.device_info.getIMEI", "Gets IMEI (slot 1)", "sunmi.tms.device",
            exampleParameters = "{}",
            exampleOutput = """{"result":"123456789012345"}"""),
        MethodDescriptor("sunmi.tms.device.device_info.getIMEIBySlotIndex", "Gets IMEI for specific SIM slot", "sunmi.tms.device",
            exampleParameters = """{"slotIndex":0}""",
            exampleOutput = """{"result":"123456789012345"}"""),
        MethodDescriptor("sunmi.tms.device.device_info.getIMSI", "Gets IMSI (preferred SIM)", "sunmi.tms.device",
            exampleParameters = "{}",
            exampleOutput = """{"result":"123456789012345"}"""),
        MethodDescriptor("sunmi.tms.device.device_info.getIMSIBySlotIndex", "Gets IMSI for specific SIM slot", "sunmi.tms.device",
            exampleParameters = """{"slotIndex":0}""",
            exampleOutput = """{"result":"123456789012345"}"""),
        MethodDescriptor("sunmi.tms.device.device_info.getFullICCID", "Gets full ICCID for SIM slot", "sunmi.tms.device",
            exampleParameters = """{"slotIndex":0}""",
            exampleOutput = """{"result":"89860000000000000000"}"""),
        MethodDescriptor("sunmi.tms.device.device_info.getSystemProperty", "Gets system property by key", "sunmi.tms.device",
            exampleParameters = """{"key":"ro.product.model"}""",
            exampleOutput = """{"result":"T2s"}"""),
        MethodDescriptor("sunmi.tms.device.device_info.isFinancialDevice", "Checks if device is financial-certified", "sunmi.tms.device",
            exampleParameters = "{}",
            exampleOutput = """{"result":false}"""),
        MethodDescriptor("sunmi.tms.device.device_info.isInnerScannerSupported", "Checks if built-in scanner is supported", "sunmi.tms.device",
            exampleParameters = "{}",
            exampleOutput = """{"result":true}"""),
        MethodDescriptor("sunmi.tms.device.device_info.isInnerPrinterSupported", "Checks if built-in printer is supported", "sunmi.tms.device",
            exampleParameters = "{}",
            exampleOutput = """{"result":true}"""),
        MethodDescriptor("sunmi.tms.device.device_info.getGmsFlag", "Checks if device has GMS (Google Mobile Services)", "sunmi.tms.device",
            exampleParameters = "{}",
            exampleOutput = """{"result":true}"""),
        MethodDescriptor("sunmi.tms.device.device_info.verifyCrp", "Verifies CRP package. Blocking operation.", "sunmi.tms.device",
            experimental = true,
            exampleParameters = """{"filePath":"/sdcard/file.crp"}""",
            exampleOutput = """{"result":true}"""),
        MethodDescriptor("sunmi.tms.device.device_info.installCrp", "Installs CRP package. Blocking operation.", "sunmi.tms.device",
            experimental = true,
            superRequired = true,
            exampleParameters = """{"filePath":"/sdcard/file.crp"}""",
            exampleOutput = """{"result":true}"""),
        MethodDescriptor("sunmi.tms.device.device_info.getCrpType", "Gets CRP type (0=custom, 1=general)", "sunmi.tms.device",
            experimental = true,
            exampleParameters = """{"filePath":"/sdcard/file.crp"}""",
            exampleOutput = """{"result":0}"""),
        MethodDescriptor("sunmi.tms.device.device_info.getCrpVersion", "Gets installed CRP version", "sunmi.tms.device",
            experimental = true,
            exampleParameters = """{"crpType":0}""",
            exampleOutput = """{"result":"1.0.0"}"""),
        MethodDescriptor("sunmi.tms.device.device_info.getPciHardwareVersion", "Gets the PCI hardware version", "sunmi.tms.device",
            exampleParameters = "{}",
            exampleOutput = """{"result":"1.0.0"}"""),
        MethodDescriptor("sunmi.tms.device.device_info.getBatteryInfo", "Gets detailed battery information (level, status, capacity, health, cycle count, etc.)", "sunmi.tms.device",
            exampleParameters = "{}",
            exampleOutput = """{"result":{"batteryLevel":85,"batteryStatus":2,"batteryHealth":2,"batteryCycleCount":120,"isSupportBattery":1}}"""),
    )

    private fun buildDeviceManagerMethods() = listOf(
        MethodDescriptor("sunmi.tms.device.device_manager.setSystemTime", "Sets device system time", "sunmi.tms.device",
            superRequired = true,
            exampleParameters = """{"second":0,"minute":0,"hour":12,"day":1,"month":1,"year":2026}""",
            exampleOutput = """{}"""),
        MethodDescriptor("sunmi.tms.device.device_manager.powerReboot", "Restarts the device", "sunmi.tms.device",
            superRequired = true,
            exampleParameters = "{}",
            exampleOutput = """{}"""),
        MethodDescriptor("sunmi.tms.device.device_manager.shutdown", "Shuts down the device", "sunmi.tms.device",
            superRequired = true,
            exampleParameters = "{}",
            exampleOutput = """{}"""),
        MethodDescriptor("sunmi.tms.device.device_manager.setTimeZone", "Sets device time zone", "sunmi.tms.device",
            superRequired = true,
            exampleParameters = """{"timeZone":"Asia/Shanghai"}""",
            exampleOutput = """{}"""),
        MethodDescriptor("sunmi.tms.device.device_manager.factoryReset", "Restores factory settings", "sunmi.tms.device",
            superRequired = true,
            exampleParameters = "{}",
            exampleOutput = """{}"""),
        MethodDescriptor("sunmi.tms.device.device_manager.toSleep", "Puts device to sleep mode", "sunmi.tms.device",
            exampleParameters = "{}",
            exampleOutput = """{}"""),
        MethodDescriptor("sunmi.tms.device.device_manager.toWakeUp", "Wakes up the device", "sunmi.tms.device",
            exampleParameters = "{}",
            exampleOutput = """{}"""),
        MethodDescriptor("sunmi.tms.device.device_manager.setBootAnimation", "Sets boot animation from ZIP file", "sunmi.tms.device",
            experimental = true,
            superRequired = true,
            exampleParameters = """{"filePath":"/sdcard/bootanimation.zip"}""",
            exampleOutput = """{}"""),
        MethodDescriptor("sunmi.tms.device.device_manager.enableBluetooth", "Enables or disables Bluetooth", "sunmi.tms.device",
            exampleParameters = """{"enable":true}""",
            exampleOutput = """{}"""),
        MethodDescriptor("sunmi.tms.device.device_manager.switchBTModuleEnable", "Shows or hides Bluetooth module in settings", "sunmi.tms.device",
            exampleParameters = """{"enable":true}""",
            exampleOutput = """{}"""),
        MethodDescriptor("sunmi.tms.device.device_manager.isBTModuleEnabled", "Checks if Bluetooth module is enabled in settings", "sunmi.tms.device",
            exampleParameters = "{}",
            exampleOutput = """{"result":true}"""),
        MethodDescriptor("sunmi.tms.device.device_manager.setCustomKeyFunction", "Sets custom key function mapping", "sunmi.tms.device",
            superRequired = true,
            exampleParameters = """{"key":"volume_1","type":"none","value":"volume_up"}""",
            exampleOutput = """{}"""),
        MethodDescriptor("sunmi.tms.device.device_manager.setPowerButtonEnabled", "Enables or disables power button short-press", "sunmi.tms.device",
            superRequired = true,
            exampleParameters = """{"enabled":true}""",
            exampleOutput = """{}"""),
        MethodDescriptor("sunmi.tms.device.device_manager.isPowerButtonEnabled", "Checks power button short-press state", "sunmi.tms.device",
            exampleParameters = "{}",
            exampleOutput = """{"result":true}"""),
        MethodDescriptor("sunmi.tms.device.device_manager.setWallpaper", "Sets device wallpaper from image file", "sunmi.tms.device",
            superRequired = true,
            exampleParameters = """{"filePath":"/sdcard/wallpaper.png"}""",
            exampleOutput = """{}"""),
        MethodDescriptor("sunmi.tms.device.device_manager.setScreenBrightness", "Sets screen brightness (0-255)", "sunmi.tms.device",
            exampleParameters = """{"value":128}""",
            exampleOutput = """{}"""),
        MethodDescriptor("sunmi.tms.device.device_manager.getScreenBrightness", "Gets current screen brightness value", "sunmi.tms.device",
            exampleParameters = "{}",
            exampleOutput = """{"result":128}"""),
        MethodDescriptor("sunmi.tms.device.device_manager.setScreenTimeout", "Sets screen timeout in milliseconds", "sunmi.tms.device",
            exampleParameters = """{"timeout":30000}""",
            exampleOutput = """{}"""),
        MethodDescriptor("sunmi.tms.device.device_manager.setBrightnessMode", "Sets auto-brightness mode (0=manual, 1=auto)", "sunmi.tms.device",
            exampleParameters = """{"mode":0}""",
            exampleOutput = """{}"""),
        MethodDescriptor("sunmi.tms.device.device_manager.getMinimumScreenBrightnessSetting", "Gets minimum settable screen brightness", "sunmi.tms.device",
            exampleParameters = "{}",
            exampleOutput = """{"result":10}"""),
        MethodDescriptor("sunmi.tms.device.device_manager.getMaximumScreenBrightnessSetting", "Gets maximum settable screen brightness", "sunmi.tms.device",
            exampleParameters = "{}",
            exampleOutput = """{"result":255}"""),
        MethodDescriptor("sunmi.tms.device.device_manager.setDeviceOwner", "Sets device owner app", "sunmi.tms.device",
            experimental = true,
            superRequired = true,
            exampleParameters = """{"packageName":"com.example.app","classFullPathName":"com.example.app.AdminReceiver"}""",
            exampleOutput = """{}"""),
        MethodDescriptor("sunmi.tms.device.device_manager.clearDeviceOwner", "Clears device owner", "sunmi.tms.device",
            superRequired = true,
            exampleParameters = "{}",
            exampleOutput = """{}"""),
        MethodDescriptor("sunmi.tms.device.device_manager.enableAutoTime", "Enables or disables auto time sync", "sunmi.tms.device",
            exampleParameters = """{"enable":true}""",
            exampleOutput = """{}"""),
        MethodDescriptor("sunmi.tms.device.device_manager.enableAutoTimeZone", "Enables or disables auto timezone", "sunmi.tms.device",
            exampleParameters = """{"enable":true}""",
            exampleOutput = """{}"""),
        MethodDescriptor("sunmi.tms.device.device_manager.enableLocation", "Enables or disables location services", "sunmi.tms.device",
            exampleParameters = """{"enable":true}""",
            exampleOutput = """{}"""),
        MethodDescriptor("sunmi.tms.device.device_manager.set24Hour", "Sets 24-hour time format", "sunmi.tms.device",
            exampleParameters = """{"is24Hour":true}""",
            exampleOutput = """{}"""),
        MethodDescriptor("sunmi.tms.device.device_manager.setAirplaneMode", "Enables or disables airplane mode", "sunmi.tms.device",
            exampleParameters = """{"open":true}""",
            exampleOutput = """{}"""),
        MethodDescriptor("sunmi.tms.device.device_manager.setPhysicKeyEnabled", "Sets physical key availability (type: 0=Fn, 1=*)", "sunmi.tms.device",
            experimental = true,
            exampleParameters = """{"type":0,"enable":true}""",
            exampleOutput = """{}"""),
        MethodDescriptor("sunmi.tms.device.device_manager.getPhysicKeyEnabled", "Gets physical key availability (type: 0=Fn, 1=*)", "sunmi.tms.device",
            experimental = true,
            exampleParameters = """{"type":0}""",
            exampleOutput = """{"result":true}"""),
        MethodDescriptor("sunmi.tms.device.device_manager.enableGPS", "Enables or disables GPS", "sunmi.tms.device",
            exampleParameters = """{"isEnable":true}""",
            exampleOutput = """{}"""),
        MethodDescriptor("sunmi.tms.device.device_manager.enableWIFI", "Enables or disables Wi-Fi", "sunmi.tms.device",
            exampleParameters = """{"isEnable":true}""",
            exampleOutput = """{}"""),
        MethodDescriptor("sunmi.tms.device.device_manager.enableNFC", "Enables or disables NFC", "sunmi.tms.device",
            exampleParameters = """{"enable":true}""",
            exampleOutput = """{}"""),
        MethodDescriptor("sunmi.tms.device.device_manager.getDeviceDockStatus", "Gets the device dock/cradle status", "sunmi.tms.device",
            experimental = true,
            exampleParameters = "{}",
            exampleOutput = """{"result":0}"""),
        MethodDescriptor("sunmi.tms.device.device_manager.getDefaultUsbMode", "Gets the default USB mode", "sunmi.tms.device",
            experimental = true,
            exampleParameters = "{}",
            exampleOutput = """{"result":0}"""),
        MethodDescriptor("sunmi.tms.device.device_manager.setDefaultUsbMode", "Sets the default USB mode", "sunmi.tms.device",
            experimental = true,
            superRequired = true,
            exampleParameters = """{"mode":0}""",
            exampleOutput = """{"result":0}"""),
        MethodDescriptor("sunmi.tms.device.device_manager.supportsBuiltinLed", "Reports built-in RGB LED support (CPad). status: supported | unsupported | invalid_rom | no_service | <code>", "sunmi.tms.device",
            exampleParameters = "{}",
            exampleOutput = """{"result":true,"status":"supported"}"""),
        MethodDescriptor("sunmi.tms.device.device_manager.getNfcReaderCardemulationStatus", "Gets the NFC reader card-emulation status", "sunmi.tms.device",
            experimental = true,
            exampleParameters = "{}",
            exampleOutput = """{"result":0}"""),
        MethodDescriptor("sunmi.tms.device.device_manager.setNfcReaderCardemulationStatus", "Sets the NFC reader card-emulation status", "sunmi.tms.device",
            experimental = true,
            superRequired = true,
            exampleParameters = """{"status":1}""",
            exampleOutput = """{"result":0}"""),
        MethodDescriptor("sunmi.tms.device.device_manager.deleteTTSVoicePackageCache", "Deletes cached TTS voice packages by name", "sunmi.tms.device",
            experimental = true,
            exampleParameters = """{"names":["en-US","zh-CN"]}""",
            exampleOutput = """{"result":0}"""),
        MethodDescriptor("sunmi.tms.device.device_manager.installTTSVoicePackage", "Installs a TTS voice package. Async — resolves with the result Bundle.", "sunmi.tms.device",
            experimental = true,
            superRequired = true,
            exampleParameters = """{"type":0,"path":"/sdcard/tts.zip"}""",
            exampleOutput = """{"result":0}"""),
    )

    private fun buildRuntimeMethods() = listOf(
        MethodDescriptor("sunmi.tms.device.runtime.getGPSLocation", "Gets cached GPS location", "sunmi.tms.device",
            exampleParameters = "{}",
            exampleOutput = """{"result":{"longitude":"116.397128","latitude":"39.916527","altitude":"50.0","speed":"0.0","bearing":"0.0"}}"""),
        MethodDescriptor("sunmi.tms.device.runtime.getGPSLocationWithTimeout", "Gets real-time GPS location. Async — emits gpsLocationChanged event.", "sunmi.tms.device",
            exampleParameters = """{"timeout":10000}""",
            exampleOutput = """{}"""),
        MethodDescriptor("sunmi.tms.device.runtime.getNetworkLocationWithTimeout", "Gets real-time network-based location. Async — emits networkLocationChanged event.", "sunmi.tms.device",
            exampleParameters = """{"timeout":10000}""",
            exampleOutput = """{}"""),
        MethodDescriptor("sunmi.tms.device.runtime.getBatteryCapacity", "Gets battery level percentage string", "sunmi.tms.device",
            exampleParameters = "{}",
            exampleOutput = """{"result":"85%"}"""),
        MethodDescriptor("sunmi.tms.device.runtime.getRamTotalSize", "Gets total RAM in bytes", "sunmi.tms.device",
            exampleParameters = "{}",
            exampleOutput = """{"result":4294967296}"""),
        MethodDescriptor("sunmi.tms.device.runtime.getRamUsedSize", "Gets used RAM in bytes", "sunmi.tms.device",
            exampleParameters = "{}",
            exampleOutput = """{"result":2147483648}"""),
        MethodDescriptor("sunmi.tms.device.runtime.getRomTotalSize", "Gets total storage capacity in bytes", "sunmi.tms.device",
            exampleParameters = "{}",
            exampleOutput = """{"result":32212254720}"""),
        MethodDescriptor("sunmi.tms.device.runtime.getRomUsedSize", "Gets used storage capacity in bytes", "sunmi.tms.device",
            exampleParameters = "{}",
            exampleOutput = """{"result":16106127360}"""),
        MethodDescriptor("sunmi.tms.device.runtime.getCpuUsage", "Gets CPU usage percentage", "sunmi.tms.device",
            exampleParameters = "{}",
            exampleOutput = """{"result":10.5}"""),
        MethodDescriptor("sunmi.tms.device.runtime.getTurnOnMills", "Gets device boot time in milliseconds", "sunmi.tms.device",
            exampleParameters = "{}",
            exampleOutput = """{"result":1234567890}"""),
    )
}
